### ISSUE TITLE
Find a name for our Project

### ISSUE THREAD

**Issue by osmannnurikar** [bounswe/bounswe2016group10#16]
Please write your suggestions as comments. Engish or Turkish is preferred

**Comment by kcgebologlu** [comment]
findit
bulbeni
buldunmu
bulgaç
buldurgaç
bulduru

**Comment by epinar** [comment]
buldur
buldur pilavi
mont beni
bulmaca
buluver
hoş bul

**Comment by tunahansalih** [comment]
tagbook
geldimgordumbuldum
tagit

**Comment by furkankav** [comment]
bildirbil
maptag
arayanbulur
osenibulur

**Comment by batu23** [comment]
bence turkce isim olmasin)
-"taggit"
-"tagger"
-"taglife"

**Comment by tunahansalih** [comment]
**Taglife** is selected as the name of the project
