### ISSUE TITLE
Create software Requirement Specification

### ISSUE THREAD

**Issue by tunahansalih** [bounswe/bounswe2016group10#17]
1. Introduction
1.1 Purpose
1.2 Document conventions
1.3 Intended audience
1.4 Additional information
1.5 Contact information/SRS team members
1.6 References
2. Overall Description
2.1 Product perspective
2.2 Product functions
2.3 User classes and characteristics
2.4 Operating environment
2.5 User environment
2.6 Design/implementation constraints
2.7 Assumptions and dependencies
3. External Interface Requirements
3.1 User interfaces
3.2 Hardware interfaces
3.3 Software interfaces
3.4 Communication protocols and interfaces
4. System Features
4.1 System feature A
4.1.1 Description and priority
4.1.2 Action/result
4.1.3 Functional requirements
4.2 System feature B
5. Other Nonfunctional Requirements
5.1 Performance requirements
5.2 Safety requirements
5.3 Security requirements
5.4 Software quality attributes
5.5 Project documentation
5.6 User documentation
6. Other Requirements
Appendix A: Terminology/Glossary/Definitions list
Appendix B: To be determine

**Comment by osmannnurikar** [comment]
An alternative format for Requirement Specification
1.	Executive Summary
1.1	Project Overview
1.2	Purpose and Scope of this Specification
2.	Product/Service Description
2.1	Product Context
2.2	User Characteristics
2.3	Assumptions
2.4	Constraints
2.5	Dependencies
3.	Requirements
3.1	Functional Requirements	
3.2	User Interface Requirements
3.3	Usability
3.4	Performance
3.4.1	Capacity
3.4.2	Availability
3.4.3	Latency
3.5	Manageability/Maintainability
3.5.1	Monitoring
3.5.2	Maintenance
3.5.3	Operations
3.6	System Interface/Integration
3.6.1	Network and Hardware Interfaces
3.6.2	Systems Interfaces
3.7	Security
3.7.1	Protection
3.7.2	Authorization and Authentication
3.8	Data Management
3.9	Standards Compliance
3.10	Portability	
4.	User Scenarios/Use Cases
5.	Deleted or Deferred Requirements
6.	Requirements Confirmation/Stakeholder sign-off
APPENDIX	
Appendix A.	Definitions, Acronyms, and Abbreviations
Appendix B.	References
Appendix C.	Requirements Traceability Matrix
Appendix D.	Organizing the Requirements

**Comment by osmannnurikar** [comment]
[Requirement Specification](https://github.com/bounswe/bounswe2016group10/wiki/Requirement-Analysis) has been created and documented on Wiki
