### ISSUE TITLE
Meeting Todos:

### ISSUE THREAD

**Issue by epinar** [bounswe/bounswe2016group10#41]
- Refine requirements
- Refine mockups
- Choose the milestones and refine planning according to the recommended calendar
- Make a research for development environment and prepare computers
- Update Wiki

Some suggestions for the meeting: 
- Since we are one of the most crowded groups, It's hard to accomplish something in the meeting or decide to big issues. 
- We can do a brief talk in first 15 minutes, something like a catch up. 
- Then, it would be helpful to divide into groups of 2-3 people. One group refining requirements, the other for mockups, another for planning and so on... 
- After 45 minutes of working in seperate groups, we can come together again to show us what we have done. 30 minutes will be enough for that.
- Set up the development environments on computers.

**Comment by tunahansalih** [comment]
Perfect. Hope to see everyone in meeting.
