### ISSUE TITLE
Check out these videos! 

### ISSUE THREAD

**Issue by epinar** [bounswe/bounswe2016group10#7]
A) Watch the following videos and document your observations on GitHub:

1. Scrum in Under 10 Minutes : [1](https://www.youtube.com/watch?v=XU0llRltyFM)
2. Patrick Lencioni: Five Dysfunctions Of a Team [2](https://www.youtube.com/watch?v=6sqvWEI1CVg&spfreload=10)

Optional videos:

1. Toyota Production System - 5S Just, Just in Time, Kaisen : [3](https://www.youtube.com/watch?v=kce2L23yLcw )

2. Dan Pink: The puzzle of motivation : [4](https://www.youtube.com/watch?v=rrkrvAUbU9Y)

**Comment by osmannnurikar** [comment]
Videos has been watched and documented:
* [Scrum in Under 10 Minutes](https://github.com/bounswe/bounswe2016group10/wiki/Scrum:-SWE-creates-products-planning--and-using-advanced-timing-methodologies)
* [Patrick Lencioni: Five Dysfunctions Of a Team](https://github.com/bounswe/bounswe2016group10/wiki/Patrick-Lencioni:-Five-Dysfunctions-Of-a-Team)

Additionally the most interesting part of Toyota Production System is "the ability of any member in production line can stop the whole production if he sees this necessary". Not a leader, not an executive, not the production owner... just a team member can decide and act on it.
